feat(parkinhyo): Goal for the 3rd week of Dec.
Road-of-CODEr/stupid-week pull request #169
Opened 2020-12-13 03:47 UTC by PARKINHYO

## 완료된 목표 3가지를 적어주세요

1. 교양 - 실용금융이해 정리
2. 교양 - 고용과 법률 정리
3. 알고리즘 인터뷰 9장 스택, 큐
   * 일일온도
   * 큐를 이용한 스택 구현

## 다음주 목표 3가지를 적어주세요

1. 알고리즘 인터뷰 9장 스택, 큐
   * 스택을 이용한 큐 구현
   * 원형 큐 디자인]
2. 알고리즘 인터뷰 10장
3. 오픽 공부 계획 짜기

2020-12-13 08:49 UTC, juheekimm approved these changes
올리실때 Assignees 설정 본인으로 해서 올려주시면 더 좋을 것 같아요~!
고생하셨습니다! 👍

2020-12-13 08:49 UTC, juheekimm commented on 2020/12/week2/parkinhyo/README.md
> +2. 교양 - [고용과 법률 정리](./elective%20-%20고법.md)
와우 교양과목 난이도가.. 장난아니네요 ㅋㅋㅋ

2020-12-13 08:49 UTC, juheekimm commented on 2020/12/week2/parkinhyo/README.md
> +   * [큐를 이용한 스택 구현](./큐를%20이용한%20스택%20구현.py)
저는 이책 사놓고 아직 못열어봤는데..ㅋㅋㅋ 이책 읽을만한가요?? 궁금ㅎㅎ

2020-12-13 09:19 UTC, PARKINHYO commented on 2020/12/week2/parkinhyo/README.md
> +2. 교양 - [고용과 법률 정리](./elective%20-%20고법.md)
> 올리실때 Assignees 설정 본인으로 해서 올려주시면 더 좋을 것 같아요~!
> 고생하셨습니다! 👍
넵 잘 몰라서 누르다가 다시 빼버렸네요... 다음 pr 때 확인하겠습니다..!!

2020-12-13 09:22 UTC, PARKINHYO commented on 2020/12/week2/parkinhyo/README.md
> +   * [큐를 이용한 스택 구현](./큐를%20이용한%20스택%20구현.py)
책 좋은 것 같아요. 난이도가 쉬운 책이라는데 저한테는 어렵네요...ㅎㅎ

2020-12-13 11:57 UTC, juheekimm commented on 2020/12/week2/parkinhyo/README.md
> +2. 교양 - [고용과 법률 정리](./elective%20-%20고법.md)
제가 다시 추가했어요~
![image](https://user-images.githubusercontent.com/26156701/102011143-c598c400-3d85-11eb-947c-f5ed13590b9c.png)
이렇게 하시면 됩니다 ㅎㅎ

2020-12-13 12:05 UTC, PARKINHYO commented on 2020/12/week2/parkinhyo/README.md
> +2. 교양 - [고용과 법률 정리](./elective%20-%20고법.md)
> 제가 다시 추가했어요~
> ![](https://user-images.githubusercontent.com/26156701/102011143-c598c400-3d85-11eb-947c-f5ed13590b9c.png)
> 이렇게 하시면 됩니다 ㅎㅎ

감사합니다!!!

2020-12-13 13:41 UTC, nook1208 approved these changes
고생하셨습니다 ~

2020-12-13 14:05 UTC, PARKINHYO commented
> 고생하셨습니다 ~

감사합니다!!

2020-12-13 14:09 UTC, minhyungPark approved these changes
수고하셨습니다 👍

2020-12-13 14:11 UTC, minhyungPark commented on 2020/12/week1/1ilsang/README.md
> -## 이번주 목표
왜 해당 파일이 삭제되었을까요??

2020-12-13 14:19 UTC, PARKINHYO commented on 2020/12/week1/1ilsang/README.md
> -## 이번주 목표
> 왜 해당 파일이 삭제되었을까요??
제 브랜치에 1ilsang님 파일이 있어서 지웠습니다. 저번에 들어간 것 같아요 ㅠㅡㅠ

2020-12-13 14:30 UTC, minhyungPark commented on 2020/12/week1/1ilsang/README.md
> -## 이번주 목표
[커밋내역](https://github.com/PARKINHYO/stupid-week/commits/parkinhyo) 확인해보니 이 파일은 1ilsang님이 추가하셨던거 같고, 추가한 이후에 fork 받으셔서 파일이 있는게 맞습니다.
이 파일을 지워서 지금 confilct이 나는데 다시 복구시켜주시겠어요?

2020-12-13 14:32 UTC, minhyungPark commented on 2020/12/week1/1ilsang/README.md
> -## 이번주 목표
아 이부분 커밋내역 확인해보니까 1ilsang님이 추가했다가 다시 삭제하시고 현재는 새롭게 추가된 상태네요.
흠.. @1ilsang 님 이 부분 처리 어떻게 해야할까요?

2020-12-13 16:23 UTC, 1ilsang requested changes
@PARKINHYO @minhyungPark 
[Diff](https://github.com/Road-of-CODEr/stupid-week/pull/169/files/f2760baa215c79082b08551975158e48e9076b36#diff-d6032f9b7335feb2c56c344c51bd32d47f97d683e9bba266f77b57264e8cfe72)

rebase 로 현재 master 기준으로 컨플릭 해결해 주시는게 좋을거 같네요.

어려우시면 스무링하게 브랜치 날리시고 마스터 기준으로 다시 받으시는걸 추천드리겠습니다.

번거롭겠지만 재푸쉬 부탁드리겠습니다.

2020-12-14 03:40 UTC, PARKINHYO commented
> @PARKINHYO @minhyungPark
> [Diff](https://github.com/Road-of-CODEr/stupid-week/pull/169/files/f2760baa215c79082b08551975158e48e9076b36#diff-d6032f9b7335feb2c56c344c51bd32d47f97d683e9bba266f77b57264e8cfe72)
> 
> rebase 로 현재 master 기준으로 컨플릭 해결해 주시는게 좋을거 같네요.
> 
> 어려우시면 스무링하게 브랜치 날리시고 마스터 기준으로 다시 받으시는걸 추천드리겠습니다.
> 
> 번거롭겠지만 재푸쉬 부탁드리겠습니다.

![image](https://user-images.githubusercontent.com/47745785/102037528-aa22cd00-3e08-11eb-8c8d-cb564fdc9e29.png)

충돌이 나진 않는거 같은데 이렇게 하면 될까요??

```bash
$ git rebase master

First, rewinding head to replay your work on top of it...
Applying: feat(parkinhyo): Fix Project Structure
.git/rebase-apply/patch:32: trailing whitespace.
DTI(Debt to Income ratio) : 총부채상환비율. 주책이나 부동산을 담보로 돈을 빌리려 할 때 고객의 부채부담 능력을 측정하는 지표
.git/rebase-apply/patch:34: trailing whitespace.
LTV(Loan to Value ratio) : 주택담보대출인정비율. 담보 대비 대출금액의 비율을 나타내는 지표.
.git/rebase-apply/patch:60: trailing whitespace.
불법채권추심 : 채권자가 채무상환을 독촉하는 과정에서 관련 법규를 위반하는 것.
.git/rebase-apply/patch:66: trailing whitespace.
위험: 어떤 상황이 발생할지 여부가 불확실 + 발생 시 결과가 부정적.
.git/rebase-apply/patch:86: trailing whitespace.
### 보험의 기초
warning: squelched 10 whitespace errors
warning: 15 lines add whitespace errors.
Using index info to reconstruct a base tree...
M       2020/12/week1/1ilsang/README.md
Falling back to patching base and 3-way merge...
CONFLICT (modify/delete): 2020/12/week1/1ilsang/README.md deleted in feat(parkinhyo): Fix Project Structure and modified in HEAD. Version HEAD of 2020/12/week1/1ilsang/README.md left in tree.
error: Failed to merge in the changes.
hint: Use 'git am --show-current-patch' to see the failed patch
Patch failed at 0001 feat(parkinhyo): Fix Project Structure
Resolve all conflicts manually, mark them as resolved with
"git add/rm <conflicted_files>", then run "git rebase --continue".
You can instead skip this commit: run "git rebase --skip".
To abort and get back to the state before "git rebase", run "git rebase --abort".

$ git add (충돌난파일)
$ git rebase --continue
$ git commit -m "~"
$ git push origin parkinhyo
```

이런식으로 해줬습니다...!

2020-12-15 14:21 UTC, 1ilsang approved these changes
네 고생하셨습니다!

2020-12-15 14:21 UTC, merged

2020-12-15 14:54 UTC, PARKINHYO commented
> 네 고생하셨습니다!

감사합니다!!