feat: next week to do list
Road-of-CODEr/stupid-week pull request #172
Opened 2020-12-13 12:00 UTC by InyoungJ

## 완료된 목표 3가지를 적어주세요

✅ minor: [1. Database Tuning - 친절한 SQL 튜닝 책으로 공부하기 chapt3,4](https://www.notion.so/4-7f97a0f0c537424e928ac6b35c8ef9b1)

✅ minor: [2. Python Flask 시작 : 파이썬 웹 프로그래밍 보기](https://www.notion.so/Flask-65cefcf6f4a849749030e03ed79a380f)

✅ minor: [3. 강성태 영단어 어원편 단어 암기 : 월~금 하루 50개씩 250개](https://www.notion.so/week2-98bca3d05e574067a362bd493fa52a48)

## 다음주 목표 3가지를 적어주세요

1. Database Tuning - 친절한 SQL 튜닝 책으로 공부하기 chapt4(sort merge join, hash join)

2. Python Flask 시작 : 파이썬 웹 프로그래밍 -  minitwit

3. 강성태 영단어 어원편 단어 암기 : 월~금 하루 2day씩 20day까지

2020-12-13 13:46 UTC, nook1208 approved these changes
이번 주 엄청 많은 단어를 외우셨군요 대단합니다 :+1:

2020-12-13 16:25 UTC, 1ilsang requested changes
![image](https://user-images.githubusercontent.com/23524849/102017610-461deb80-3dab-11eb-9c7b-f68f60d679af.png)

파일 경로가 이상한거 같아요. 닉네임으로 폴더화 부탁드리겠습니다!

2020-12-14 06:57 UTC, InyoungJ commented
@1ilsang 요 페이지에서 경로 추가해서 commit 새로 찍었는데, 혹시 로컬에서 push 를 다시 해야할까요?

2020-12-15 14:22 UTC, 1ilsang approved these changes
넵 고생하셨습니다

2020-12-15 15:04 UTC, juheekimm approved these changes
고생하셨습니다! 👍👍

2020-12-15 15:05 UTC, merged